before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- main: ./cmd/jira-to-tripletex/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapcrafts:
  - license: Apache-2.0
    publish: true
brews:
  - tap:
      owner: cobraz
      name: homebrew-tools
    commit_author:
      name: Simen A. W. Olsen
      email: cobraz@cobraz.no
    homepage: https://github.com/cobraz/jira-to-tripletex
    folder: Formula
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
